package main

const queriesTemplate = `
// Code generated by go generate; DO NOT EDIT.
package main

import "database/sql"

// 以主键ID查询
func (u *User) QueryByID(db *sql.DB) error {
	// Implementation of the query logic
	return nil
}

// 按名称查询
func (u *User) QueryByName(db *sql.DB) error {
	// Implementation of the query logic
	return nil
}

// 按 ID 查询产品
func (p *Product) QueryByID(db *sql.DB) error {
	// Implementation of the query logic
	return nil
}

// 以名称查询产品
func (p *Product) QueryByName(db *sql.DB) error {
	// Implementation of the query logic
	return nil
}
`
